"""Changed site model name

Revision ID: 3bb531e1b8d3
Revises: 632e600cf7c7
Create Date: 2021-03-19 11:04:35.523157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb531e1b8d3'
down_revision = '632e600cf7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
