"""removed default values from model

Revision ID: 632e600cf7c7
Revises: 69b6c1b323a8
Create Date: 2021-03-16 12:10:06.331821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e600cf7c7'
down_revision = '69b6c1b323a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
