"""Added depth and park-approach column

Revision ID: 69b6c1b323a8
Revises: 
Create Date: 2021-03-16 11:15:03.951086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b6c1b323a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('park_approach', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'park_approach')
    op.drop_column('sites', 'depth')
    # ### end Alembic commands ###
