"""Fix site model name bug

Revision ID: c3e135d4b153
Revises: 3bb531e1b8d3
Create Date: 2021-03-19 11:10:45.134614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e135d4b153'
down_revision = '3bb531e1b8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
